### ISSUE TITLE
Firefox: Open connection problem

### ISSUE THREAD

**Issue by luklewluk** [kiler129/TinyWs#3]
Firefox is the only web browser which cannot connect to TinyWs. According to the browser's log, connection protocol is incompatible. The problem is probably caused by difference between outgoing headers sending by Firefox and other browsers:

[Firefox]
Connection: close
Connection: keep-alive

[Other browsers]
Connection: close,keep-alive

**Comment by kiler129** [comment]
Actually other browsers are sending only single `Connection` with value of `Upgrade`. That behaviour is defined by [RFC6455, sec. 1.2](https://tools.ietf.org/html/rfc6455#page-5).  
As I can see Firefox uses non-standard `Connection` header with value of `keep-alive, Upgrade`. TinyWs checks whatever `Connection` header equals `Upgrade` - that's why connection fails.

**Comment by kiler129** [comment]
[Issue fixed in master branch](https://github.com/kiler129/TinyWs/commit/5e9cdd13a1ceb74b0b6627fb70069ed5df0d0b0f).
